# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_MEMORY = "512"
VMNAME = "pullrequestsdeploys"
TRAVIS_PULL_REQUEST = "SAMPLE_PULL_REQUEST"
NODE_VER = "10.x"

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
ETH0IP=$(ifconfig -a eth0 | grep "inet addr:")
echo "Networking: [$ETH0IP]"
SCRIPT

Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |vb, orvb|
		orvb.vm.box = "bento/ubuntu-16.04"
		orvb.vm.synced_folder '../', '/home/vagrant/yakchat', create:true, :mount_options => ['dmode=775', 'fmode=777']
		orvb.vm.network "private_network", ip: "192.168.86.8"
		vb.memory = SERVER_MEMORY
		vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
	end

	config.vm.provider "hyperv" do |hv, orhv|
		orhv.vm.box = "generic/ubuntu1604"
		orhv.vm.synced_folder "../", "/home/vagrant/yakchat", create:true,
			type: "rsync", rsync__exclude: ".git/"
		orhv.vm.network "public_network"
		hv.memory = SERVER_MEMORY
		hv.maxmemory = SERVER_MEMORY
		hv.linked_clone = true
		hv.enable_virtualization_extensions = true
		hv.vmname = VMNAME
	end

	config.vm.define "pullrequestsdeploys", primary:true do |comlog|
		comlog.vm.hostname = "pullrequestsdeploys.test"
		comlog.vm.provision "shell", inline: $script
		comlog.vm.provision :shell do |s|
			s.path = "travis.provision.sh"
			s.env = {
				"TRAVIS_PULL_REQUEST" => TRAVIS_PULL_REQUEST,
				"VAGRANT_PROVISION" => 1
			}
		end
	end
end
